### ISSUE TITLE
Randomize pivot value in implementation of quick sort algorithm, 

### ISSUE THREAD

**Issue by Mystigan** [Mystigan/DSA-with-Go#1]
Currently, the last element is always picked as the pivot. Randomize this such that the pivot is a random number between the "start" and "end" indices passed to the partition function.
Test your solution properly before opening a PR.

**Comment by nikhilreddydev** [comment]
@Mystigan can I work on it?

**Comment by nikhilreddydev** [comment]
@Mystigan Please review my PR and give me feedback.
